### ISSUE TITLE
A version that does not require to open java/base

### ISSUE THREAD

**Issue by meronbrouwer** [GedMarc/JWebMPDevKit#2]
Is it likely that a future version will not require the vm argument to open  java/base to guice?

cheers,
meron

**Comment by GedMarc** [comment]
Definitely Yes, a byte-buddy enhanced version rather than the CGLib implementation in Guice is coming,

You can ref here
https://github.com/google/guice/issues/1133 

In addition to @mcculls I am also doing the same

**Comment by meronbrouwer** [comment]
That is great news. Thanks for the info!

**Comment by GedMarc** [comment]
Resolved in 1.0.5.1 :)
